# Generated by Django 5.1.3 on 2024-11-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voyage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("NomChauffeur", models.CharField(max_length=100)),
                ("plaque", models.CharField(max_length=100)),
                ("NbrPlaceVide", models.IntegerField()),
                ("VilleDepart", models.CharField(max_length=100)),
                ("VilleArrivee", models.CharField(max_length=100)),
                ("heureDepart", models.TimeField()),
                ("HeureArrive", models.TimeField()),
                ("Prix", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
