# Generated by Django 5.1.3 on 2024-11-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voyage", "0002_remove_voyage_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="voyage",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
