# Generated by Django 5.1.3 on 2024-11-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voyage", "0004_voyage_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voyage",
            name="HeureArrive",
        ),
    ]
